#!/usr/bin/env python3
"""
骨架生成器 - 为未匹配的图表生成模块骨架
Skeleton Generator - Generate module skeleton for unmatched charts

功能 | Features:
- 生成标准的 R Markdown 结构
- 填充识别到的信息
- 创建占位符代码
- 提供完成指南
"""

import os
from typing import Dict, List, Any
from pathlib import Path
from datetime import datetime


class SkeletonGenerator:
    """骨架生成器类 | Skeleton Generator class"""

    def __init__(self):
        """
        初始化生成器
        Initialize generator
        """
        pass

    def generate_skeleton(self, chart_info: Dict[str, Any], output_dir: str) -> Path:
        """
        生成模块骨架
        Generate module skeleton

        参数 | Parameters:
            chart_info: 图表信息 | Chart information
            output_dir: 输出目录 | Output directory

        返回 | Returns:
            骨架模块路径 | Skeleton module path
        """
        chart_type = chart_info.get("chart_type", "unknown")
        figure_number = chart_info.get("figure_number", "1")

        # 创建目录
        # Create directory
        module_name = f"FigureYa_Figure{figure_number}_{chart_type}_skeleton"
        module_path = Path(output_dir) / module_name
        module_path.mkdir(parents=True, exist_ok=True)

        print(f"Generating skeleton module: {module_name}")

        # 生成 Rmd 文件
        # Generate Rmd file
        rmd_content = self._generate_skeleton_rmd(chart_info)
        rmd_path = module_path / f"{module_name}.Rmd"
        with open(rmd_path, "w", encoding="utf-8") as f:
            f.write(rmd_content)

        print(f"  Created: {rmd_path.name}")

        # 生成 install_dependencies.R
        # Generate install_dependencies.R
        dep_content = self._generate_dependencies(chart_info)
        dep_path = module_path / "install_dependencies.R"
        with open(dep_path, "w", encoding="utf-8") as f:
            f.write(dep_content)

        print(f"  Created: {dep_path.name}")

        # 生成 README.md（完成指南）
        # Generate README.md (completion guide)
        readme_content = self._generate_skeleton_readme(chart_info)
        readme_path = module_path / "README.md"
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)

        print(f"  Created: {readme_path.name}")

        # 复制图片作为参考
        # Copy image as reference
        image_path = chart_info.get("image_path")
        if image_path and Path(image_path).exists():
            ref_image_path = module_path / "reference_image.png"
            import shutil
            shutil.copy2(image_path, ref_image_path)
            print(f"  Created: reference_image.png")

        print(f"\n✓ Skeleton module created at: {module_path}")

        return module_path

    def _generate_skeleton_rmd(self, chart_info: Dict[str, Any]) -> str:
        """
        生成骨架 Rmd 内容
        Generate skeleton Rmd content

        参数 | Parameters:
            chart_info: 图表信息 | Chart information

        返回 | Returns:
            Rmd 内容 | Rmd content
        """
        chart_type = chart_info.get("chart_type", "unknown")
        evidence = chart_info.get("evidence", {})
        figure_number = chart_info.get("figure_number", "1")

        # 识别到的 R 包
        # Identified R packages
        r_packages = evidence.get("text", {}).get("r_packages", [])
        visual_type = evidence.get("visual", {}).get("identified_type", "Unknown")

        # 基础包
        # Base packages
        base_packages = ["ggplot2", "dplyr"]
        all_packages = list(set(base_packages + r_packages))

        rmd_content = f"""---
title: "FigureYa {chart_type.replace('_', ' ').title()} - TODO: Add specific title"
params:
  author: "Your Name"
  reviewer: "Reviewer Name"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: flatly
    highlight: tango
    code_folding: show
---

**Author(s)**: `r params$author`
**Reviewer(s)**: `r params$reviewer`
**Date**: `r Sys.Date()`

## Academic Citation
If you use this code in your work or research, we kindly request that you cite our publication:

Xiaofan Lu, et al. (2025). FigureYa: A Standardized Visualization Framework for Enhancing Biomedical Data Interpretation and Research Efficiency. iMetaMed. https://doi.org/10.1002/imm3.70005

---

## ⚠️ 注意：这是一个模块骨架

这个模块是由 `figureya-pdf-parser` 自动生成的骨架，需要手动完成以下部分：

**Important: This is a skeleton module auto-generated by `figureya-pdf-parser`. You need to complete the following parts manually:**

- [ ] 编写实际的绘图代码
- [ ] Write actual plotting code
- [ ] 准备示例数据
- [ ] Prepare example data
- [ ] 测试并验证输出
- [ ] Test and validate output
- [ ] 完善参数设置
- [ ] Complete parameter settings

查看 `README.md` 了解完成步骤。
See `README.md` for completion steps.

---

## 需求描述 Requirement description

TODO: 添加图表描述
TODO: Add chart description

**识别信息 | Identified Information:**
- 图表类型 | Chart Type: {chart_type}
- 视觉识别 | Visual Recognition: {visual_type}
- 识别置信度 | Confidence: {chart_info.get('confidence', 0):.2f}
- 来源 | Source: Figure {figure_number}

![](reference_image.png)

## 应用场景 Application scenario

TODO: 添加应用场景说明
TODO: Add application scenario description

### 方法原理和特点
TODO: 添加方法原理
TODO: Add method principles

### 具体使用场景
TODO: 添加使用场景
TODO: Add specific use cases

### 数据要求
TODO: 添加数据要求
TODO: Add data requirements

## 环境设置 Environment setting

```{{r}}
source("install_dependencies.R") #安装所需R包 | Install required R packages
```

## 输入文件 Input file

TODO: 添加输入文件说明
TODO: Add input file description

- `easy_input_data.csv`，[文件用途说明]
- `easy_input_data.csv`, [File description]

至少包含以下列：[列名和含义]
At least include the following columns: [Column names and meanings]

```{{r}}
# 读取数据
# Read data
# x <- read.csv("easy_input_data.csv")
```

## 参数设置 Parameter setting

TODO: 添加参数说明
TODO: Add parameter description

**根据具体需求调整**
**Adjust according to specific needs**

```{{r}}
# 参数设置
# Parameter settings
# param1 <- value1  # 参数说明 | Parameter description
# param2 <- value2  # 参数说明 | Parameter description
```

## 开始画图 Start drawing

TODO: 添加绘图代码
TODO: Add plotting code

**识别到的 R 包 | Identified R packages:** {', '.join(r_packages) if r_packages else 'None'}

```{{r}}
# 加载必要的包
# Load required packages
library(ggplot2)
library(dplyr)
{chr(10).join([f'library({pkg})' for pkg in r_packages]) if r_packages else '# Load additional packages as needed'}

# 绘图代码
# Plotting code
# TODO: 根据参考图片实现绘图逻辑
# TODO: Implement plotting logic based on reference image

# p <- ggplot(data, aes(x = x, y = y)) +
#   geom_*(...) +
#   theme_*() +
#   labs(...)
```

## 保存结果 Save results

```{{r}}
# 保存 PDF
# Save PDF
# ggsave("output.pdf", p, width = 10, height = 8)
```

---

## 骨架生成信息 | Skeleton Generation Information

- **生成时间 | Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **识别置信度 | Confidence**: {chart_info.get('confidence', 0):.2f}
- **视觉识别类型 | Visual Type**: {visual_type}
- **识别到的 R 包 | Identified R packages**: {', '.join(r_packages) if r_packages else 'None'}
- **原始图片 | Original image**: reference_image.png

## 完成检查清单 | Completion Checklist

完成模块后，确认以下项目：

After completing the module, confirm the following:

- [ ] 所有 TODO 项已完成
- [ ] All TODO items completed
- [ ] 代码可以正常运行
- [ ] Code runs without errors
- [ ] 生成的图表符合预期
- [ ] Generated chart meets expectations
- [ ] 参数可以调整
- [ ] Parameters are adjustable
- [ ] 文档完整清晰
- [ ] Documentation is complete and clear
- [ ] 示例数据已准备
- [ ] Example data prepared
- [ ] 删除了"注意：这是一个模块骨架"章节
- [ ] Removed "Important: This is a skeleton module" section

## 需要帮助？| Need Help?

1. 查看现有 FigureYa 模块作为参考
   - Review existing FigureYa modules for reference
2. 使用 `figureya-creator` skill 寻求帮助
   - Use `figureya-creator` skill for help
3. 阅读 R 包文档
   - Read R package documentation
4. 在 GitHub 上提 issue
   - Open an issue on GitHub

---

**下一步 | Next Step**: 查看 `README.md` 了解详细的完成步骤
**Next Step**: See `README.md` for detailed completion steps
"""

        return rmd_content

    def _generate_dependencies(self, chart_info: Dict[str, Any]) -> str:
        """
        生成依赖安装脚本
        Generate dependency installation script

        参数 | Parameters:
            chart_info: 图表信息 | Chart information

        返回 | Returns:
            脚本内容 | Script content
        """
        evidence = chart_info.get("evidence", {})
        r_packages = evidence.get("text", {}).get("r_packages", [])

        # 基础包
        # Base packages
        base_packages = ["ggplot2", "dplyr"]

        # 合并识别到的包
        # Merge identified packages
        all_packages = list(set(base_packages + r_packages))

        dep_content = f"""# FigureYa 模块依赖包安装脚本
# Installation script for FigureYa module dependencies

packages <- c(
{', '.join([f'"{pkg}"' for pkg in all_packages])}
)

# 检查并安装未安装的包
# Check and install packages that are not installed
new_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

# 加载所有包
# Load all packages
lapply(packages, require, character.only = TRUE)

# 如果需要 Bioconductor 包
# If Bioconductor packages are needed
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# bioc_packages <- c("Bioconductor包名")
# new_bioc_packages <- bioc_packages[!(bioc_packages %in% installed.packages()[,"Package"])]
# if(length(new_bioc_packages)) BiocManager::install(new_bioc_packages)

# lapply(bioc_packages, require, character.only = TRUE)

cat("所有依赖包安装完成！| All dependencies installed successfully!\\n")
"""

        return dep_content

    def _generate_skeleton_readme(self, chart_info: Dict[str, Any]) -> str:
        """
        生成骨架说明文档
        Generate skeleton readme document

        参数 | Parameters:
            chart_info: 图表信息 | Chart information

        返回 | Returns:
            README 内容 | README content
        """
        chart_type = chart_info.get("chart_type", "unknown")
        figure_number = chart_info.get("figure_number", "1")

        readme_content = f"""# 模块骨架完成指南
# Module Skeleton Completion Guide

## 概述 | Overview

这是一个由 `figureya-pdf-parser` 自动生成的模块骨架。
This is a skeleton module auto-generated by `figureya-pdf-parser`.

它包含了基本的结构，但需要你手动完成核心代码部分。
It contains the basic structure, but you need to manually complete the core code parts.

**图表信息 | Chart Information:**
- 类型 | Type: {chart_type}
- 来源 | Source: Figure {figure_number}
- 置信度 | Confidence: {chart_info.get('confidence', 0):.2f}

---

## 完成步骤 | Completion Steps

### 步骤 1：理解需求 | Step 1: Understand Requirements

查看 `reference_image.png`，理解需要绘制的内容：
Review `reference_image.png` to understand what needs to be plotted:

- [ ] 图表类型 | Chart type
- [ ] 数据结构 | Data structure
- [ ] 视觉元素 | Visual elements
- [ ] 关键特征 | Key features

### 步骤 2：准备数据 | Step 2: Prepare Data

**重要 | Important**: 使用真实的示例数据，而不是 AI 生成的假数据。
**Important**: Use real example data, not AI-generated fake data.

为什么需要真实数据？| Why real data?
- 更有代表性，包含实际的数据特征
- More representative, contains actual data characteristics
- 你更了解数据，能更好地解释结果
- You know the data better and can explain results
- 确保数据格式符合实际应用场景
- Ensures data format matches actual use cases

准备以下内容 | Prepare the following:
- [ ] CSV 格式的数据文件 | CSV format data file
- [ ] 列名清晰 | Clear column names
- [ ] 包含示例数据 | Include example data
- [ ] 数据量合理 | Reasonable data size

### 步骤 3：编写代码 | Step 3: Write Code

在 R Markdown 文件中找到标记为 `TODO` 的部分，完成代码编写：
Find sections marked `TODO` in the R Markdown file and complete the code:

#### 3.1 需求描述 | Requirement Description

```
描述你想要画什么类型的图，或者从文献中看到的效果。
Describe what type of chart you want to draw or the effect seen in the literature.

Draw a beautiful [chart type] like this one in the paper.
```

#### 3.2 应用场景 | Application Scenario

```
添加方法的原理、使用场景、数据要求等。
Add method principles, use cases, data requirements, etc.
```

#### 3.3 输入文件 | Input File

```
说明数据文件格式和列含义。
Explain data file format and column meanings.
```

#### 3.4 参数设置 | Parameter Setting

```
设置可调整的参数，并标注需要用户修改的部分。
Set adjustable parameters and mark parts users need to modify.
```

#### 3.5 绘图代码 | Plotting Code

```
这是核心部分。参考识别到的 R 包编写代码。
This is the core part. Write code referencing the identified R packages.

识别到的包 | Identified packages: {', '.join(chart_info.get('evidence', {}).get('text', {}).get('r_packages', []))}
```

### 步骤 4：测试验证 | Step 4: Test and Validate

```bash
# 在 R 或 RStudio 中运行
# Run in R or RStudio
rmarkdown::render("FigureYa_Figure{figure_number}_{chart_type}_skeleton.Rmd")
```

检查并确认 | Check and confirm:
- [ ] 代码能正常运行 | Code runs without errors
- [ ] 生成的图表符合预期 | Generated chart meets expectations
- [ ] 参数可以调整 | Parameters are adjustable
- [ ] 文档完整清晰 | Documentation is complete and clear
- [ ] HTML 报告正常生成 | HTML report generates correctly

### 步骤 5：完善文档 | Step 5: Refine Documentation

- [ ] 删除"注意：这是一个模块骨架"章节
- [ ] Remove "Important: This is a skeleton module" section
- [ ] 完善"需求描述"和"应用场景"
- [ ] Complete "Requirement description" and "Application scenario"
- [ ] 添加示例图片（生成后）
- [ ] Add example image (after generation)
- [ ] 检查所有章节完整
- [ ] Check all sections complete

### 步骤 6：最终检查 | Step 6: Final Check

使用完成检查清单：
Use the completion checklist in the Rmd file:

- [ ] 所有 TODO 项已完成 | All TODO items completed
- [ ] 代码可以正常运行 | Code runs without errors
- [ ] 生成的图表符合预期 | Generated chart meets expectations
- [ ] 参数可以调整 | Parameters are adjustable
- [ ] 文档完整清晰 | Documentation is complete and clear
- [ ] 示例数据已准备 | Example data prepared
- [ ] 删除了骨架说明章节 | Removed skeleton notice sections

---

## 参考资源 | Reference Resources

### 相似模块 | Similar Modules

查看现有的 FigureYa 模块作为参考：
Review existing FigureYa modules for reference:

- 基础统计图 | Basic statistics: FigureYa01-10
- 组学分析 | Genomics analysis: FigureYa20-40
- 生存分析 | Survival analysis: FigureYa70-80
- 复杂图表 | Complex charts: FigureYa90-100

### R 包文档 | R Package Documentation

根据识别到的包查阅文档：
Check documentation for identified packages:

{chr(10).join([f"- [{pkg}](https://cran.r-project.org/package={pkg})" for pkg in chart_info.get('evidence', {}).get('text', {}).get('r_packages', [])]) if chart_info.get('evidence', {}).get('text', {}).get('r_packages', []) else "- 查阅相关 R 包文档 | Check relevant R package documentation"}

### 代码示例 | Code Examples

- R Graph Gallery: https://r-graph-gallery.com/
- ggplot2 文档: https://ggplot2.tidyverse.org/
- GitHub 上的 FigureYa 模块 | FigureYa modules on GitHub

---

## 获取帮助 | Get Help

如果遇到问题：
If you encounter problems:

1. **参考现有模块 | Reference existing modules**
   - 查找类似的可视化
   - Find similar visualizations
   - 学习代码结构
   - Learn code structure

2. **使用 figureya-creator skill | Use figureya-creator skill**
   - 在 Claude Code 中提问
   - Ask questions in Claude Code
   - 提供参考图片和需求
   - Provide reference image and requirements

3. **查看 FigureYa 文档 | Check FigureYa documentation**
   - FigureYa Wiki: https://github.com/ying-ge/FigureYa/wiki
   - 示例和教程 | Examples and tutorials

4. **在 GitHub 上提 issue | Open an issue on GitHub**
   - 描述问题和需求
   - Describe problem and requirements
   - 附上代码和错误信息
   - Attach code and error messages

---

## 完成后 | After Completion

模块完成后，你可以：
After completing the module, you can:

1. **使用这个模块进行数据分析**
   - Use this module for data analysis
2. **分享给其他人使用**
   - Share with others for use
3. **贡献回 FigureYa 项目**（如果觉得有价值）
   - Contribute back to FigureYa project (if valuable)
4. **作为其他模块的模板**
   - Use as template for other modules

---

## 提示和建议 | Tips and Suggestions

### 代码实现 | Code Implementation

1. **从简单开始 | Start simple**
   - 先实现基本功能
   - Implement basic features first
   - 逐步添加复杂功能
   - Gradually add complex features

2. **使用标准模式 | Use standard patterns**
   - 参考 ggplot2 标准语法
   - Reference ggplot2 standard syntax
   - 保持代码清晰
   - Keep code clear

3. **添加注释 | Add comments**
   - 关键步骤添加说明
   - Add explanations for key steps
   - 双语文档
   - Bilingual documentation

### 参数设置 | Parameter Settings

1. **提供合理默认值 | Provide reasonable defaults**
   - 适用于大多数场景
   - Work for most scenarios
   - 易于理解和调整
   - Easy to understand and adjust

2. **标注重要参数 | Mark important parameters**
   - 使用清晰的变量名
   - Use clear variable names
   - 添加说明注释
   - Add explanatory comments

3. **支持灵活调整 | Support flexible adjustment**
   - 颜色、尺寸、标签
   - Colors, dimensions, labels
   - 数据阈值
   - Data thresholds

### 数据准备 | Data Preparation

1. **使用真实数据 | Use real data**
   - 避免随机生成
   - Avoid random generation
   - 确保代表性
   - Ensure representativeness

2. **提供示例 | Provide examples**
   - 清晰的列名
   - Clear column names
   - 数据格式说明
   - Data format explanation

3. **测试边界情况 | Test edge cases**
   - 缺失值处理
   - Handle missing values
   - 异常值处理
   - Handle outliers

---

**祝你好运！| Good luck!**

如果你成功完成了这个模块，考虑分享给其他人或贡献回 FigureYa 项目！
If you successfully complete this module, consider sharing it with others or contributing it back to the FigureYa project!

---

生成时间 | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

        return readme_content


def main():
    """主函数 | Main function"""
    import argparse
    import json

    parser = argparse.ArgumentParser(
        description="生成模块骨架 | Generate module skeleton"
    )
    parser.add_argument(
        "input_json",
        help="输入 JSON 文件（包含图表信息）| Input JSON file (containing chart info)"
    )
    parser.add_argument(
        "-o", "--output",
        default="output",
        help="输出目录 | Output directory"
    )

    args = parser.parse_args()

    # 检查输入文件是否存在
    # Check if input file exists
    if not Path(args.input_json).exists():
        print(f"Error: File not found: {args.input_json}")
        return 1

    # 读取输入数据
    # Read input data
    with open(args.input_json, "r", encoding="utf-8") as f:
        chart_info = json.load(f)

    # 创建生成器并生成
    # Create generator and generate
    generator = SkeletonGenerator()
    skeleton_path = generator.generate_skeleton(chart_info, args.output)

    print(f"\n✓ Skeleton module successfully created!")
    print(f"Path: {skeleton_path}")
    print(f"\nNext steps:")
    print(f"1. Review the skeleton at: {skeleton_path}")
    print(f"2. Read README.md for completion guide")
    print(f"3. Complete the TODO sections in the Rmd file")

    return 0


if __name__ == "__main__":
    exit(main())
